### ISSUE TITLE
Filter Option

### ISSUE THREAD

**Issue by crazy0codes** [crazy0codes/Messages#5]
Create the filter option for Chat 
you can take help from the @VijayMalli43  
If you want

**Comment by narasimhavk18** [comment]
completed my task 
transfer remaining amount

**Comment by narasimhavk18** [comment]
completed my task
transfer remaining amount

**Comment by narasimhavk18** [comment]
ok team leader

**Comment by crazy0codes** [comment]
Redo your work again

**Comment by narasimhavk18** [comment]
done

**Comment by crazy0codes** [comment]
Good

**Comment by VijayMalli43** [comment]
finger print fellow
